== Expert Team on Information Management

=== Terms of Reference

[loweralpha]
. In close collaboration with SERCOM, lead a critical review of the Manual on High Quality Global Data Management Framework for Climate (WMO-No. 1238), ensuring consistency with the WMO Earth system approach and harmonization of the standard and recommended practices related to climate data and observations across the Technical Regulations;
. Maintain and develop recommended practices and technical guidance material for information management to meet the needs of Members:
[lowerroman]
.. Develop technical guidance on implementing FAIR Principles and support the development of a FAIR scoreboard for data shared on WIS2;
.. In close collaboration with SERCOM, review and develop technical resources and best practices related to historical records management and data rescue;
.. In close collaboration with SERCOM and HMEI, develop the minimum technical specifications of a climate data management system deemed compliant with the WMO Climate Data Management System Specifications (WMO-No. 1131);
. Review and propose updates to incorporate standards and practices for information management in the Manual on WIS (WMO No. 1060) and Guide to the WIS (WMO No. 1061).

=== Deliverables / tasks (ordered by priority)

[loweralpha]
. Proposed revisions to the Manual on High Quality Global Data Management Framework for Climate (WMO-No. 1238);
. Proposed minimal technical specifications for a CDMS compliant with the Climate Data Management System Specifications (WMO-No. 1131);
. Technical guidance on implementing the FAIR Principles and development of a FAIR scoreboard for datasets shared on the WIS2.
