== Expert Team on Metadata Standards

=== Terms of Reference

[loweralpha]
. Develop and maintain WMO standards for metadata (discovery, observations, provenance, WIS2 notifications, WIS2 topic hierarchy, and WIS2 monitoring / alerting) based on the W3C, OGC and ISO/TC 211 series of international standards to meet the needs of Members, WIS, WIGOS, WMO Earth system disciplines/domains and partner organizations;
. Documentation of the WMO metadata standards in the:
[lowerroman]
.. Manual on WIS (WMO 1060), Vol. II;
.. Guide to WIS (WMO-No. 1061), Vol. II;
.. Manual on Codes (WMO-No. 306), Vol I.3;
.. WIGOS Metadata Standard (WMO-No. 1192);
.. Manual on WIGOS (WMO-No. 1160) - Appendix 2.4 The WIGOS Metadata Standard
.. Guide to WIGOS (WMO-No. 1165) - 3. WIGOS Metadata
. Develop and maintain quality assessment frameworks in order to facilitate the continuous improvement of metadata management, discovery and use;
. Collaborate with relevant standards bodies (such as OGC and ISO) to ensure that the metadata requirements and standards are harmonized to meet the needs and reduce the operational impact to WMO members;
. Perform a comparative analysis of WMO Core Metadata Profile v2, WIS Notification Message, WIGOS Metadata Standard, vocabularies, and use of persistent identifiers in order to provide recommendations and options on future evolution and/or harmonization;
. Evaluate, recommend and improve tools to facilitate the metadata management lifecycle (create, publish, update, discover and harvest), giving priority to tools for automated harvesting and editing; 
. Prepare best practices and guidelines to support implementation;
. Maintain and further develop the content of codes.wmo.int as required by the metadata standards.
