== Expert Team on WIS2 Development Programme

=== Terms of Reference

[loweralpha]
. Develop a training program to support Members in the implementation of WIS2,
. Develop, in collaboration with the Capacity Development Panel, a competency framework for WIS2,
. Contribute to the implementation of WIS 2.0  with a focus on addressing the needs of all WMO Regional Associations and Programmes,
. Work with the Secretariat, Regional Associations, and Programmes to support the successful implementation of WIS 2.0 using proven change management practices,
. Ensure that the requirements from all Regional Associations and Programmes are satisfied according to WIS 2.0 Technical Regulations and WIS Implementation Approach,
. Organize regular feedback on WIS 2.0 from Members and from all Regional Associations and Programmes,
. Contribute and facilitate the active participation of Members from all Regional Associations and Programmes in WIS 2.0 related projects,
. Support the GISCs to ensure successful implementation of WIS in their area of responsibility.
