== Task Team on Open Source

=== Terms of Reference

[loweralpha]
. In close collaboration with SERCOM, define specific roles and responsibilities of INFCOM and SERCOM in managing and guiding open-source initiatives.
. Coordinate closely with SERCOM throughout the development of an open-source framework to ensure alignment and complementarity of efforts. 
. Establish guidelines for the integration of open-source projects in alignment with WMO's technical regulations and standards. 
. Propose mechanisms for ensuring that open-source development aligns with and accelerates the implementation of key WMO initiatives, particularly Early Warnings for All.
. Develop and manage a risk register to identify any associated risks with using open-source by WMO Members.
. Develop strategies and establish guidelines to support Members' digital transformation efforts through open-source solutions. 
. Outline processes for continuous feedback and improvement in WMO's open-source ecosystem. 
. Manage relationships with external open-source communities and coordinate with UN-wide open-source initiatives.
. Prepare and present a draft collaborative framework for approval at INFCOM-4.
