== Task Team on Open Source

=== Terms of Reference

[loweralpha]
. Define specific roles and responsibilities for INFCOM, in consulation with SERCOM and WMO Secretariat in managing and guiding open-source initiatives. 
. Establish guidelines for the integration of open-source projects in alignment with WMO's technical regulations and standards. 
. Propose mechanisms for ensuring that open-source development aligns with and accelerates the implementation of key WMO initiatives, particularly Early Warnings for All.
. Identify and develop and manage a risk register to identify any associated risks with using open-source for WMO Members.
. Develop strategies and establish guidelines to support Members' digital transformation efforts through open-source solutions. 
. Outline processes for continuous feedback and improvement in WMO's open-source ecosystem. 
. Coordinate closely with SERCOM throughout the development of the framework to ensure alignment and complementarity of efforts. 
. Manage relationships with external open-source communities and coordinate with UN-wide open-source initiatives.
. Prepare and present a draft collaborative framework for approval at INFCOM-4.
