== Task Team on WIS2 For Hydrology and WHOS implementation 

=== Terms of Reference
.	Support the alignment of WHOS and WIS 2.0,
.	Finalize the 2024-2029 WHOS operational plan including alignment on the data exchange activities within WIS 2.0 framework, and implementation and sustainability engagement plan,
.	Propose the WIS 2.0 topic hierarchy, and discovery metadata in accordance with the WCMP 2.0 for hydrological data and products,
.	Develop hydrological data and products metadata key performance indicators (KPIs) to assess the completeness and quality of metadata records,
.	Regularly report to the SC-IMT Expert Team and hydrological community through appropriate Hydrology INFCOM body on the progress of the task team activities,
.	Propose updates to manuals, guides and other technical regulation documents and updates to relevant chapters in the documents, related to hydrological data exchange and access as part of WIS.
.	Liaise with the Expert Team on WIS2 Development Program to engage the participation of hydrology stakeholders in the implementation of WIS 2.0,
.	Lead the implementation of WHOS among Members at national, regional and international scales, as per Cg-19 request (4.2(4)/24), in collaboration with other UN Organizations, academia, and regional/international organizations,
.	Develop capacity building and training materials on WHOS and engage in capacity development for Members in collaboration with ETR and other capacity building groups within WMO, academia, and regional organizations (basins and commissions).
